version: '3'

services:
  api:
    build:
      context: .
    ports:
      - 3000:3000
    env_file:
      - ./.env.api
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=sparkusr
      - POSTGRES_PASSWORD=sparkpass
      - POSTGRES_DB=sparkdb
    ports:
      - 5432:5432

volumes:
  postgres_data: